[build]
  functions = "netlify/functions"

# Main logging job (18:00 / 6:00 PM)
[functions.scheduleTimeLog]
  schedule = "0 18 * * 1-5"

# Backup check at 6:05 AM for the previous day
[functions.recheckAndLogIfNeeded]
  schedule = "5 6 * * 1-5"
