[build]
  functions = "netlify/functions"

# Main logging job at 6:00 PM (Kyiv Time)
[functions.scheduleTimeLog]
  schedule = "0 18 * * 1-5"

# Re-check if logging was successful at 6:05 PM (Kyiv Time)
[functions.recheckAndLogIfNeeded]
  schedule = "5 18 * * 1-5"