[build]
  functions = "netlify/functions"

# Main logging job at 6:00 PM
[functions.scheduleTimeLog]
  schedule = "0 18 * * 1-5"

# Backup check at 9:05 PM
[functions.recheckAndLogIfNeeded]
  schedule = "5 21 * * 1-5"
